// ============================================
// Universal Project Manager - Type Definitions
// ============================================

/**
 * Supported project types
 */
export type ProjectType =
  | 'software_development'
  | 'marketing_campaign'
  | 'course_creation'
  | 'event_planning'
  | 'product_launch'
  | 'research_project'
  | 'content_creation'
  | 'construction'
  | 'business_operations'
  | 'creative_project'
  | 'custom';

/**
 * User experience levels - affects time estimates
 */
export type ExperienceLevel = 'novice' | 'intermediate' | 'expert';

/**
 * Task status types
 */
export type TaskStatus = 'pending' | 'in-progress' | 'complete' | 'blocked' | 'on-hold';

/**
 * Project metadata
 */
export interface ProjectMeta {
  name: string;
  description?: string;
  initialPrompt?: string;              // The original AI prompt used to create the project
  projectType: ProjectType;
  experienceLevel: ExperienceLevel;
  lead?: string;
  status: 'planning' | 'in-progress' | 'on-hold' | 'completed';
  startDate?: string;
  targetEndDate?: string;
  budget?: number;
  timeline?: string;
  collaborators?: Collaborator[];      // Team members who can be assigned tasks
}

/**
 * Collaborator/Team member
 */
export interface Collaborator {
  id: string;
  name: string;
  email?: string;
  role?: string;
  color?: string;                       // Color for avatar/badges
  initials?: string;                    // e.g., "JD" for John Doe
}

/**
 * Time log entry for tracking work sessions
 */
export interface TimeLog {
  id: string;
  date: string;                         // ISO date string
  hours: number;                        // Hours worked in this session
  notes?: string;                       // What was done in this session
  loggedBy?: string;                    // Collaborator ID who logged the time
}

/**
 * Individual task definition
 */
export interface Task {
  id: string;
  task: string;
  phase: string;
  phaseTitle: string;
  category: string;
  baseEstHours?: number;           // Base time estimate before experience adjustment
  adjustedEstHours: number;        // Adjusted for experience level
  sopReference?: string;           // Standard Operating Procedure reference
  dependencies?: string[];         // IDs of tasks this depends on
  criticalPath?: boolean;          // Is this on the critical path?
  aiGenerated?: boolean;           // Was this task generated by AI?
  notes?: string;                  // Task notes/description
  assignedTo?: string;             // Collaborator ID assigned to this task
}

/**
 * Task state tracking (user progress)
 */
export interface TaskState {
  estHours?: number;               // Estimated hours (adjusted)
  actualHours?: string;            // Actual hours spent (legacy - calculated from timeLogs)
  status?: TaskStatus;             // Current status
  notes?: string;                  // User notes
  blockedReason?: string;          // Why is task blocked
  completedDate?: string;          // When was it completed
  timeLogs?: TimeLog[];            // Detailed time tracking entries
}

/**
 * Phase definition
 */
export interface Phase {
  phaseId: string;
  phaseTitle: string;
  description: string;
  color: string;
  typicalDuration: number;         // Days
  sopReference?: string;
}

/**
 * Risk factor
 */
export interface RiskFactor {
  category: string;
  description: string;
  severity: 'low' | 'medium' | 'high';
  mitigation: string;
}

/**
 * AI Analysis Request
 */
export interface AIAnalysisRequest {
  projectDescription: string;
  projectType: ProjectType;
  experienceLevel: ExperienceLevel;
  budget?: number;
  timeline?: string;
  teamSize?: number;
}

/**
 * AI Analysis Response
 */
export interface AIAnalysisResponse {
  suggestedTasks: Task[];
  suggestedPhases: Phase[];
  estimatedTimeline: string;
  riskFactors: RiskFactor[];
  recommendations: string[];
  confidence: number;               // 0-1 confidence score
}

/**
 * Progress statistics
 */
export interface Stats {
  overall: {
    total: number;
    completed: number;
    inProgress: number;
    blocked: number;
  };
  totalEst: number;
  totalActual: number;
  overruns: number;
}

/**
 * AI-generated progress report
 */
export interface AIReport {
  generatedAt: string;
  projectId: string;
  analysis: {
    progressAssessment: string;
    schedulePerformance: string;
    costPerformance: string;
    qualityMetrics: string;
  };
  recommendations: {
    immediate: string[];
    shortTerm: string[];
    longTerm: string[];
  };
  predictiveInsights: {
    completionForecast: string;
    budgetForecast: string;
    riskAreas: RiskFactor[];
  };
  exportData: {
    rawMetrics: any;
    formattedReport: string;
    apiPayload: any;
  };
}

/**
 * Project template
 */
export interface ProjectTemplate {
  id: string;
  name: string;
  projectType: ProjectType;
  phases: Phase[];
  standardTasks: Task[];
  bestPractices: string[];
  commonPitfalls?: string[];
  estimatedDuration?: string;
  skillsRequired?: string[];
}

/**
 * Export format types
 */
export type ExportFormat = 'csv' | 'json' | 'pdf' | 'api';

/**
 * Move history for undo functionality
 */
export interface MoveHistory {
  taskId: string;
  fromPhase: string;
  toPhase: string;
  timestamp: number;
}
